import { TUTORIAL_STEP_IDS } from './tutorialStepIds';

/** @type {import('./tutorialTypes').TutorialStep[]} */
const TUTORIAL_STEPS = [
  {
    id: TUTORIAL_STEP_IDS.INTRO,
    track: 'intro',
    title: '开始创造',
    prompt: '欢迎来到 Project Arranger。接下来你会一步步完成一段 8 小节音乐片段。',
    hint: '点击开始后进入真实编曲界面。',
    successMessage: '准备好了，我们先认识工作区。',
    target: { selector: '[data-tutorial-target="transport-play"]' },
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.UI_OVERVIEW,
    track: 'intro',
    title: '认识工作区',
    prompt: '顶部控制播放，中央显示四条音轨，底部会显示当前音轨的编辑器。',
    hint: '观察高亮区域，然后继续下一步。',
    successMessage: '界面结构已经认识，接下来从鼓开始。',
    target: { selector: '#track-overview' },
    completion: { type: 'manual' },
  },
  {
    id: TUTORIAL_STEP_IDS.PERC_KICK,
    track: 'perc',
    title: '加入 Kick',
    prompt: '在第 1 小节放入第一个 Kick，让节奏有落点。',
    hint: '选择 PERC 轨道，然后点亮 Kick 的第 1 个八分位置。',
    successMessage: 'Kick 已经给音乐踩稳第一步。',
    target: {
      selector: '[data-tutorial-target="perc-kick-step-0"]',
      trackId: 'perc',
      bar: 0,
      step: 0,
      instrument: 'kick',
    },
    completion: {
      type: 'cell-count',
      trackId: 'perc',
      bar: 0,
      instrument: 'kick',
      minCount: 1,
    },
    playback: { bars: [0], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.PERC_SNARE,
    track: 'perc',
    title: '加入 Snare',
    prompt: '在第 5 个八分位置加入 Snare，让节奏有回应。',
    hint: '点亮 Snare 的第 5 个八分位置。',
    successMessage: 'Snare 让节奏开始有问答感。',
    target: {
      selector: '[data-tutorial-target="perc-snare-step-4"]',
      trackId: 'perc',
      bar: 0,
      step: 8,
      instrument: 'snare',
    },
    completion: {
      type: 'cell-count',
      trackId: 'perc',
      bar: 0,
      instrument: 'snare',
      minCount: 1,
    },
    playback: { bars: [0], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.PERC_HIHAT,
    track: 'perc',
    title: '铺上 Hihat',
    prompt: '加入 Hihat，让律动连续起来。',
    hint: '点亮多个 Hihat 八分位置，至少完成 4 个。',
    successMessage: 'Hihat 让节奏真正跑起来了。',
    target: {
      selector: '[data-tutorial-target="perc-hihat"]',
      trackId: 'perc',
      bar: 0,
      instrument: 'hihat',
    },
    completion: {
      type: 'cell-count',
      trackId: 'perc',
      bar: 0,
      instrument: 'hihat',
      minCount: 4,
    },
    playback: { bars: [0], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.PERC_GROOVE,
    track: 'perc',
    title: '完成基础律动',
    prompt: '把 Kick、Snare 和 Hihat 组合成一小节基础 groove。',
    hint: '使用 PERC 编辑器或自动基础律动按钮完成这一小节。',
    successMessage: '第一小节鼓组完成，可以进入和弦了。',
    target: { selector: '[data-tutorial-target="perc-groove"]', trackId: 'perc', bar: 0 },
    completion: { type: 'cell-count', trackId: 'perc', bar: 0, minCount: 6 },
    playback: { bars: [0], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.CHORD_TEMPLATE,
    track: 'chord',
    title: '选择和弦模板',
    prompt: '选择一个和弦模板，先让 8 小节有完整和声骨架。',
    hint: '选择 Doo-wop / C-Am-F-G 方向的模板。',
    successMessage: '和声骨架已经写入。',
    target: { selector: '[data-tutorial-target="chord-template"]', trackId: 'chord' },
    completion: { type: 'chord-choice', stage: 'template', optionIndex: 0 },
    playback: { bars: [0, 1, 2, 3], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.CHORD_COLOR,
    track: 'chord',
    title: '替换和弦色彩',
    prompt: '用按键选择单体和弦变体，让基础和弦变得更有颜色。',
    hint: '为 4 个主要和弦各选择一个色彩变体。',
    successMessage: '和弦已经有更丰富的色彩。',
    target: { selector: '[data-tutorial-target="chord-color"]', trackId: 'chord' },
    completion: { type: 'chord-choice', stage: 'color', minCount: 4 },
    playback: { bars: [0, 1, 2, 3], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.CHORD_PASSING,
    track: 'chord',
    title: '添加经过和弦',
    prompt: '选择一个经过和弦，让两个和弦之间的移动更顺滑。',
    hint: '在 Chord Composer 的经过和弦阶段选择一个选项。',
    successMessage: '和弦之间已经有更自然的连接。',
    target: { selector: '[data-tutorial-target="chord-passing"]', trackId: 'chord' },
    completion: { type: 'chord-choice', stage: 'passing', minCount: 1 },
    playback: { bars: [0, 1, 2, 3], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.CHORD_TENSION,
    track: 'chord',
    title: '制造张力释放',
    prompt: '选择一个张力释放和弦，让段落更有戏剧感。',
    hint: '在张力释放阶段选择一个选项并确认。',
    successMessage: '这段音乐已经有了更清晰的推进感。',
    target: { selector: '[data-tutorial-target="chord-tension"]', trackId: 'chord' },
    completion: { type: 'chord-choice', stage: 'tension', minCount: 1 },
    playback: { bars: [4, 5, 6, 7], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.LEAD_PERFORMANCE,
    track: 'lead',
    title: 'Lead 即兴演奏',
    prompt: '用 Lead 音符在进行上即兴演奏，完成最后的表达。',
    hint: '按下几个 Lead 音符，听它们如何落在和弦上。',
    successMessage: 'Lead 已经加入，v0.22 教学闭环完成。',
    target: { selector: '[data-tutorial-target="lead-performance"]', trackId: 'lead' },
    completion: { type: 'lead-play', minCount: 4 },
    playback: { bars: [0, 1, 2, 3, 4, 5, 6, 7], autoStart: true },
  },
  {
    id: TUTORIAL_STEP_IDS.COMPLETE,
    track: 'intro',
    title: '完成',
    prompt: '你已经完成了一段 8 小节音乐片段，可以继续自由创作。',
    successMessage: '教程完成。',
    completion: { type: 'manual' },
  },
];

export { TUTORIAL_STEPS };
