import {
  CHORD_COMMAND_TYPES,
  LEAD_COMMAND_TYPES,
  PERC_COMMAND_TYPES,
  TRANSPORT_COMMAND_TYPES,
  TUTORIAL_COMMAND_TYPES,
} from './appCommands';

const COMMAND_TARGETS = Object.freeze({
  transport: TRANSPORT_COMMAND_TYPES,
  tutorial: TUTORIAL_COMMAND_TYPES,
  perc: PERC_COMMAND_TYPES,
  chord: CHORD_COMMAND_TYPES,
  lead: LEAD_COMMAND_TYPES,
});

export { COMMAND_TARGETS };
